name: main
on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install depencies
      run: npm install
      
    - name: Build
      run: npm run build
      
    - name: Test
      run: npm run test
      
    - name: Prepare deploy
      run: node ./prepare-pack.js build/Release/WCMAccessor.node dist WCMAccessor.node
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/
        retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs: build 
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: git config --global user.name "qQsss777" && git config --global user.email ""

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
      runs-on: windows-latest
      needs: build 
      if: startsWith(github.ref, 'refs/tags/v')
      steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
  
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
  
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
  
      - name: Configure npm for GitHub Packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc

      - name: Publish package to GitHub Packages
        run: npm publish --registry https://npm.pkg.github.com
        env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}